#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 23 15:13:45 2019

@author: charleneawillis
"""

password = 'datnigga21'
host = 'forlocalsonly.cx3latsxfbtx.us-east-2.rds.amazonaws.com'
user = 'lefty'